version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Get Dependencies
          command: GO111MODULE=on go get -v -d ./...
      - run:
          name: Build backsrv
          command: GO111MODULE=on GOOS=linux go build -v ./cmd/backsrv/
      - run:
          name: Build Golang Code (ARM)
          command: GO111MODULE=on GOARCH=arm GOOS=linux go build -v ./cmd/backsrv/
      - run:
          name: Make Installation Scripts Executable
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Install Arduino Toolchain
          command: ./.circleci/install_arduino_toolchain.sh
      - run:
          name: Build backend_arduino
          command: ./.circleci/build_backend_arduino.sh